### ISSUE TITLE
Support seconds

### ISSUE THREAD

**Issue by Faleij** [azza-bazoo/prettycron#22]
`* * * * * *` should yield "Every second".
`30 * * * * *` should yield "Every 30th second past every minute".

**Comment by rsiebeling** [comment]
Agree, I've encountered the same issue, this should be fixed I think

**Comment by bryanvpham** [comment]
I've encountered the same issue because I've been using some Golang Cron implementation. What I've found though is that nobody really supports seconds for CRON format. When using six fields, the sixth one is year and the first is minute usually. If you think about it the use cases for seconds aren't very useful anyways. If you are running something every second, you might as well just "sleep".

**Comment by qrpike** [comment]
+1

**Comment by anderssonjohan** [comment]
Ok, I've started to implement this in #28. Please give me feedback on this one.

`30 * * * * *` now prints **Every minute starting at the 30th second**
`*/30 * * * * *` now prints **Every minute starting at the first and 30th second**
